"""Rectified flow / conditional flow matching (Lipman et al. 2023,
Liu et al. 2022) with the simplest possible path: a straight line
between a noise sample and a data sample.

Forward "path": x_t = (1 - t) * x0 + t * x1,  t ~ Uniform[0, 1]
  x0 ~ N(0, I)   (noise endpoint, t=0)
  x1 ~ data      (data endpoint,  t=1)
Training target: the velocity along that path is constant in t:
  v_target = x1 - x0
so the model is trained to predict this velocity field, and sampling
integrates an ODE dx/dt = v_theta(x, t) from t=0 (noise) to t=1 (data).

This is intentionally close in spirit to DDPM so the two are easy to
compare: same UNet, same interface, different corruption path and
different training target/sampler (an ODE solver instead of a
stochastic reverse chain -- flow matching sampling is deterministic
given x0 and the step size).

Extension points:
  - swap the straight-line path for a different one (e.g. variance
    preserving, or an optimal-transport path with a schedule on sigma)
  - replace the Euler integrator in `sample` with a higher-order
    solver (Heun/RK4, or an adaptive-step ODE solver)
  - "reflow": train a second model on straightened pairs generated by
    sampling this model, to get a model whose paths are closer to
    straight lines (and so accurate in very few steps)
"""
from __future__ import annotations

import torch
import torch.nn.functional as F
from tqdm import tqdm


class RectifiedFlow:
    def __init__(self, sigma_min: float = 0.0):
        # sigma_min > 0 would blend a little noise into the t=1 endpoint
        # (as in some conditional-flow-matching variants); 0 recovers
        # plain rectified flow.
        self.sigma_min = sigma_min

    def training_loss(self, model, x1: torch.Tensor) -> torch.Tensor:
        B = x1.shape[0]
        x0 = torch.randn_like(x1)
        t = torch.rand(B, device=x1.device)
        t_ = t.view(B, *([1] * (x1.dim() - 1)))

        x_t = (1 - (1 - self.sigma_min) * t_) * x0 + t_ * x1
        v_target = x1 - (1 - self.sigma_min) * x0

        v_pred = model(x_t, t)
        return F.mse_loss(v_pred, v_target)

    @torch.no_grad()
    def sample(self, model, shape, device, steps: int = 50, progress: bool = True) -> torch.Tensor:
        """Euler integration of dx/dt = v_theta(x, t) from t=0 to t=1."""
        B = shape[0]
        x = torch.randn(shape, device=device)
        dt = 1.0 / steps
        iterator = range(steps)
        if progress:
            iterator = tqdm(iterator, total=steps, desc="Flow matching sampling")
        for i in iterator:
            t = torch.full((B,), i * dt, device=device)
            v = model(x, t)
            x = x + v * dt
        return x
